// <auto-generated />
using System;
using BiteSizedDietPlan_DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BiteSizedDietPlan_DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241121181339_mealpicreload")]
    partial class mealpicreload
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BiteSizedDietPlan_DAL.Entities.FoodEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FoodEntries");
                });

            modelBuilder.Entity("BiteSizedDietPlan_DAL.Entities.FoodEntryMeal", b =>
                {
                    b.Property<int>("FoodEntryId")
                        .HasColumnType("int");

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("FoodEntryId", "MealId");

                    b.HasIndex("MealId");

                    b.ToTable("FoodEntryMeals");
                });

            modelBuilder.Entity("BiteSizedDietPlan_DAL.Entities.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calorie")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MealCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MealCategoryId");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calorie = 250,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Yulaf Ezmesi ve Meyve"
                        },
                        new
                        {
                            Id = 2,
                            Calorie = 200,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Peynirli Omlet"
                        },
                        new
                        {
                            Id = 3,
                            Calorie = 300,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Tam Tahıllı Tost"
                        },
                        new
                        {
                            Id = 4,
                            Calorie = 250,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Avokadolu Tam Tahıllı Ekmek"
                        },
                        new
                        {
                            Id = 5,
                            Calorie = 270,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Sebzeli Gözleme"
                        },
                        new
                        {
                            Id = 6,
                            Calorie = 200,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Yoğurtlu Meyve Kasesi"
                        },
                        new
                        {
                            Id = 7,
                            Calorie = 220,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Sebzeli Omlet"
                        },
                        new
                        {
                            Id = 8,
                            Calorie = 280,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Zeytinli ve Peynirli Sandviç"
                        },
                        new
                        {
                            Id = 9,
                            Calorie = 240,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Sade Krep"
                        },
                        new
                        {
                            Id = 10,
                            Calorie = 320,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Fıstık Ezmeli Muzlu Tost"
                        },
                        new
                        {
                            Id = 11,
                            Calorie = 350,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Izgara Tavuk Salatası"
                        },
                        new
                        {
                            Id = 12,
                            Calorie = 320,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Sebzeli Kinoa"
                        },
                        new
                        {
                            Id = 13,
                            Calorie = 300,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Mercimek Çorbası ve Tam Buğday Ekmeği"
                        },
                        new
                        {
                            Id = 14,
                            Calorie = 250,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Zeytinyağlı Enginar"
                        },
                        new
                        {
                            Id = 15,
                            Calorie = 400,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Izgara Hindi ve Sebze Tabağı"
                        },
                        new
                        {
                            Id = 16,
                            Calorie = 350,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Domates Soslu Spagetti"
                        },
                        new
                        {
                            Id = 17,
                            Calorie = 320,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Nohutlu Bulgur Pilavı"
                        },
                        new
                        {
                            Id = 18,
                            Calorie = 300,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Zeytinyağlı Taze Fasulye"
                        },
                        new
                        {
                            Id = 19,
                            Calorie = 400,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Fırında Köfte ve Sebzeler"
                        },
                        new
                        {
                            Id = 20,
                            Calorie = 350,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Tavuklu Sebzeli Dürüm"
                        },
                        new
                        {
                            Id = 21,
                            Calorie = 400,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Izgara Somon ve Sebzeler"
                        },
                        new
                        {
                            Id = 22,
                            Calorie = 350,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Zeytinyağlı Barbunya"
                        },
                        new
                        {
                            Id = 23,
                            Calorie = 320,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Sebzeli Bulgur Pilavı"
                        },
                        new
                        {
                            Id = 24,
                            Calorie = 400,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Fırında Tavuk ve Patates"
                        },
                        new
                        {
                            Id = 25,
                            Calorie = 380,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Fırında Somonlu Sebze Graten"
                        },
                        new
                        {
                            Id = 26,
                            Calorie = 350,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Tavuklu Kabak Spagetti"
                        },
                        new
                        {
                            Id = 27,
                            Calorie = 300,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Balık Çorbası ve Salata"
                        },
                        new
                        {
                            Id = 28,
                            Calorie = 450,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Etli Kuru Fasulye ve Pirinç Pilavı"
                        },
                        new
                        {
                            Id = 29,
                            Calorie = 400,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Sebzeli Lazanya"
                        },
                        new
                        {
                            Id = 30,
                            Calorie = 320,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 2,
                            Name = "Fırında Karnabahar Mücveri"
                        },
                        new
                        {
                            Id = 31,
                            Calorie = 120,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 4,
                            Name = "Yoğurt ve Çilek"
                        },
                        new
                        {
                            Id = 32,
                            Calorie = 200,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 4,
                            Name = "Badem ve Ceviz Karışımı"
                        },
                        new
                        {
                            Id = 33,
                            Calorie = 150,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 4,
                            Name = "Havuç ve Humus"
                        },
                        new
                        {
                            Id = 34,
                            Calorie = 180,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 4,
                            Name = "Tam Buğday Kraker ve Peynir"
                        },
                        new
                        {
                            Id = 35,
                            Calorie = 150,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 4,
                            Name = "Elma ve Fıstık Ezmesi"
                        },
                        new
                        {
                            Id = 36,
                            Calorie = 200,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 4,
                            Name = "Muz ve Yoğurt Kasesi"
                        },
                        new
                        {
                            Id = 37,
                            Calorie = 250,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 4,
                            Name = "Protein Bar (Ev Yapımı)"
                        },
                        new
                        {
                            Id = 38,
                            Calorie = 180,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 4,
                            Name = "Cevizli Kuru Üzüm Karışımı"
                        },
                        new
                        {
                            Id = 39,
                            Calorie = 130,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 4,
                            Name = "Haşlanmış Yumurta ve Zeytin"
                        },
                        new
                        {
                            Id = 40,
                            Calorie = 200,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 4,
                            Name = "Ev Yapımı Smoothie"
                        },
                        new
                        {
                            Id = 41,
                            Calorie = 95,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Elma"
                        },
                        new
                        {
                            Id = 42,
                            Calorie = 100,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Armut"
                        },
                        new
                        {
                            Id = 43,
                            Calorie = 105,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Muz"
                        },
                        new
                        {
                            Id = 44,
                            Calorie = 62,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Portakal"
                        },
                        new
                        {
                            Id = 45,
                            Calorie = 50,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Çilek"
                        },
                        new
                        {
                            Id = 46,
                            Calorie = 42,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Kivi"
                        },
                        new
                        {
                            Id = 47,
                            Calorie = 62,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Üzüm (1 Porsiyon)"
                        },
                        new
                        {
                            Id = 48,
                            Calorie = 58,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Şeftali"
                        },
                        new
                        {
                            Id = 49,
                            Calorie = 20,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Erik (5 Adet)"
                        },
                        new
                        {
                            Id = 50,
                            Calorie = 47,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Mandalina"
                        },
                        new
                        {
                            Id = 51,
                            Calorie = 25,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Havuç (1 Adet)"
                        },
                        new
                        {
                            Id = 52,
                            Calorie = 15,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Salatalık (1 Adet)"
                        },
                        new
                        {
                            Id = 53,
                            Calorie = 30,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Biber (1 Adet)"
                        },
                        new
                        {
                            Id = 54,
                            Calorie = 22,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Domates (1 Adet)"
                        },
                        new
                        {
                            Id = 55,
                            Calorie = 10,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Kereviz Sapı (2 Dal)"
                        },
                        new
                        {
                            Id = 56,
                            Calorie = 35,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Taze Fasulye (1 Porsiyon)"
                        },
                        new
                        {
                            Id = 57,
                            Calorie = 23,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Ispanak (100 gr)"
                        },
                        new
                        {
                            Id = 58,
                            Calorie = 50,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Brokoli (1 Porsiyon)"
                        },
                        new
                        {
                            Id = 59,
                            Calorie = 25,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Karnabahar (1 Porsiyon)"
                        },
                        new
                        {
                            Id = 60,
                            Calorie = 62,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 3,
                            Name = "Bezelye (1 Porsiyon)"
                        },
                        new
                        {
                            Id = 61,
                            Calorie = 120,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Beyaz Peynir (50 gr)"
                        },
                        new
                        {
                            Id = 62,
                            Calorie = 150,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Kaşar Peyniri (50 gr)"
                        },
                        new
                        {
                            Id = 63,
                            Calorie = 180,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Tulum Peyniri (50 gr)"
                        },
                        new
                        {
                            Id = 64,
                            Calorie = 70,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Yeşil Zeytin (10 Adet)"
                        },
                        new
                        {
                            Id = 65,
                            Calorie = 75,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Siyah Zeytin (10 Adet)"
                        },
                        new
                        {
                            Id = 66,
                            Calorie = 20,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Domates ve Salatalık (100 gr)"
                        },
                        new
                        {
                            Id = 67,
                            Calorie = 68,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Haşlanmış Yumurta (1 Adet)"
                        },
                        new
                        {
                            Id = 68,
                            Calorie = 25,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Bal (1 Tatlı Kaşığı)"
                        },
                        new
                        {
                            Id = 69,
                            Calorie = 30,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Reçel (1 Tatlı Kaşığı)"
                        },
                        new
                        {
                            Id = 70,
                            Calorie = 45,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 1,
                            Name = "Tereyağı (1 Tatlı Kaşığı)"
                        },
                        new
                        {
                            Id = 71,
                            Calorie = 0,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 5,
                            Name = "Su (1 Bardak)"
                        },
                        new
                        {
                            Id = 72,
                            Calorie = 5,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 5,
                            Name = "Sade Türk Kahvesi (1 Fincan)"
                        },
                        new
                        {
                            Id = 73,
                            Calorie = 2,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 5,
                            Name = "Çay (Şekersiz, 1 Bardak)"
                        },
                        new
                        {
                            Id = 74,
                            Calorie = 120,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 5,
                            Name = "Taze Sıkılmış Portakal Suyu (1 Bardak)"
                        },
                        new
                        {
                            Id = 75,
                            Calorie = 25,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 5,
                            Name = "Limonata (Şekersiz, 1 Bardak)"
                        },
                        new
                        {
                            Id = 76,
                            Calorie = 0,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 5,
                            Name = "Yeşil Çay (Şekersiz, 1 Bardak)"
                        },
                        new
                        {
                            Id = 77,
                            Calorie = 60,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 5,
                            Name = "Ayran (1 Bardak)"
                        },
                        new
                        {
                            Id = 78,
                            Calorie = 0,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 5,
                            Name = "Soda (1 Şişe)"
                        },
                        new
                        {
                            Id = 79,
                            Calorie = 0,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 5,
                            Name = "Maden Suyu (1 Şişe)"
                        },
                        new
                        {
                            Id = 80,
                            Calorie = 80,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "C:\\Users\\msrkrk\\source\\repos\\BiteSizedDietPlan\\BiteSizedDietPlan\\Resources\\1.jpg",
                            MealCategoryId = 5,
                            Name = "Süt (Yağsız, 1 Bardak)"
                        });
                });

            modelBuilder.Entity("BiteSizedDietPlan_DAL.Entities.MealCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MealCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kahvaltılıklar"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Yemekler"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Meyve ve Sebzeler"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Atıştırmalıklar"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "İçecekler"
                        });
                });

            modelBuilder.Entity("BiteSizedDietPlan_DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BiteSizedDietPlan_DAL.Entities.FoodEntry", b =>
                {
                    b.HasOne("BiteSizedDietPlan_DAL.Entities.User", "User")
                        .WithMany("FoodEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BiteSizedDietPlan_DAL.Entities.FoodEntryMeal", b =>
                {
                    b.HasOne("BiteSizedDietPlan_DAL.Entities.FoodEntry", "FoodEntry")
                        .WithMany("FoodEntryMeals")
                        .HasForeignKey("FoodEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiteSizedDietPlan_DAL.Entities.Meal", "Meal")
                        .WithMany("FoodEntryMeals")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodEntry");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("BiteSizedDietPlan_DAL.Entities.Meal", b =>
                {
                    b.HasOne("BiteSizedDietPlan_DAL.Entities.MealCategory", "MealCategory")
                        .WithMany("Meals")
                        .HasForeignKey("MealCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealCategory");
                });

            modelBuilder.Entity("BiteSizedDietPlan_DAL.Entities.FoodEntry", b =>
                {
                    b.Navigation("FoodEntryMeals");
                });

            modelBuilder.Entity("BiteSizedDietPlan_DAL.Entities.Meal", b =>
                {
                    b.Navigation("FoodEntryMeals");
                });

            modelBuilder.Entity("BiteSizedDietPlan_DAL.Entities.MealCategory", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("BiteSizedDietPlan_DAL.Entities.User", b =>
                {
                    b.Navigation("FoodEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
